### ISSUE TITLE
Image not downloading to betterdiscord themes folder

### ISSUE THREAD

**Issue by sovietgang** [Saltssaumure/synthesis-discord-theme#13]
When i click download image usign better discord store it sends the download strait to my downlaod folder and not my themes folder

**Comment by Saltssaumure** [comment]
Hi there, I'm afraid I don't understand exactly what you mean here. Could you explain what image you're trying to download? Screenshots are welcome if you find it easier to show.

**Comment by Saltssaumure** [comment]
Issue apparently resolved on BetterDiscord discord server (browser download issue), feel free to open if this is not the case
