### ISSUE TITLE
Channel Border Not Wide Enough

### ISSUE THREAD

**Issue by lumish** [Saltssaumure/synthesis-discord-theme#14]
The border for the channels in a server cuts through that part of the window.
![crop](https://github.com/Saltssaumure/synthesis-discord-theme/assets/26492550/fd55cbcd-017b-404b-bda5-53255f51056e)

**Comment by Saltssaumure** [comment]
Cannot replicate this issue. Additionally, the server ping icon position, members table, and voice connection section look different from the current version of the theme:
![image](https://github.com/Saltssaumure/synthesis-discord-theme/assets/29710355/09c90359-5fe6-4984-b7ad-6a12eebb0f6e)
Are you using plugins, themes, or custom CSS that may be affecting the channel/server list?

**Comment by Saltssaumure** [comment]
Closing for now due to lack of response, please feel free to open this issue again if more details are available.
