### ISSUE TITLE
Discord broke all your themes

### ISSUE THREAD

**Issue by stoneshout** [Saltssaumure/synthesis-discord-theme#7]
Now they all look like this 
https://i.gyazo.com/8df0e3ad73b11eeda6e6e8daf1dc904e.png

**Comment by stoneshout** [comment]
update discord did another update so it some wat works but not entirely
https://i.gyazo.com/a6abc207c752430cc96a72fe6938f545.png

**Comment by Saltssaumure** [comment]
Fixed.
