### ISSUE TITLE
Black squares cover chat when editing a message

### ISSUE THREAD

**Issue by FestiveKillian** [Saltssaumure/synthesis-discord-theme#8]
this only happens when using the theme i checked
![image](https://github.com/Saltssaumure/synthesis-discord-theme/assets/68001279/884e4a6c-df37-451c-9b6d-98cf72e913d4)

**Comment by Saltssaumure** [comment]
Noted, will fix soon.

**Comment by Nidoskull** [comment]
Confirming this issue!
